### ISSUE TITLE
Responsive video

### ISSUE THREAD

**Issue by asela-wijesinghe** [u-wave/react-vimeo#10]
Is there a workaround for this code,
`width="1360"`

to make videos responsive and not give widths from pixels?

**Comment by goto-bus-stop** [comment]
Hmm, I believe you can also do `width="100%"`

**Comment by asela-wijesinghe** [comment]
no that's not working the video should take entire screen even` width="100vw"` is not working.you see the small video on top left corner.

![image](https://user-images.githubusercontent.com/23404276/38723656-6bc6416c-3f1f-11e8-8d3f-b4b85b496ac1.png)

**Comment by goto-bus-stop** [comment]
I'm not really sure then, sorry. This component passes the `width` and `height` values as options to the [@vimeo/player constructor](https://github.com/vimeo/player.js#embed-options) when it first loads, and sets them as DOM properties on the embed iframe element when the props change. I think setting `100vw` should work with the latter way, but the @vimeo/player constructor may require integers.

**Comment by asela-wijesinghe** [comment]
@goto-bus-stop so do you have an idea or a way to modify the widths and heights after we set fixed values to the constructor in the beginning and then modify it to '100vw' etc?

**Comment by goto-bus-stop** [comment]
it's not pretty but I think something like this _may_ work:

```js
class MyComponent extends React.Component {
  state = { mounted: false }
  componentDidMount () { 
    this.setState({ mounted: true })
  }
  render () {
    return <Vimeo width={this.state.mounted ? '100vw' : 100} ... />
  }
}
```

in theory that should first mount it as 100px wide but then immediately resize to 100vw.

**Comment by asela-wijesinghe** [comment]
That did not work @goto-bus-stop. The mounted state is working but it will not use the '100%' or '100vw' and resize to the expected size.it keeps the size we sent before mounting. :(

**Comment by azizali** [comment]
Yup didn't work for me

**Comment by azizali** [comment]
This worked for me
This is the SCSS
```
.video{
  position: relative;
  padding-bottom: 56.25%;
  padding-top: 0;
  height: 0;
  overflow: hidden;
  iframe {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
  }
}
```

This is the component
```
<Vimeo className="video"="ID_HERE"  />
```

**Comment by alexcroox** [comment]
As a `styled-component`

```
import React from 'react'
import styled from 'styled-components'
import VimeoPlayer from '@u-wave/react-vimeo'

const Vimeo = styled(VimeoPlayer)`
  position: relative;
  padding-bottom: 56.25%;
  padding-top: 0;
  height: 0;
  overflow: hidden;

  iframe {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
  }
`

export default Vimeo
```
