### ISSUE TITLE
Help with cuepoint

### ISSUE THREAD

**Issue by DaniloDaSilvaDev** [u-wave/react-vimeo#101]
I would like to change a state when the video reaches 50%. How do I use the cuepoint?

**Comment by goto-bus-stop** [comment]
I don't really know how cue points work, but most likely you'll need to use the `onReady` prop, and then use the imperative Vimeo SDK [methods for cue points](https://developer.vimeo.com/player/sdk/reference#methods-for-cue-points):

```js
const handleReady = (player) => {
  player.addCuePoint(time, data)
}
const handleCuePoint = (event) => {
  ...
}
return (
  <Vimeo
    onReady={handleReady}
    onCuePoint={handleCuePoint}
  />
)
```
