### ISSUE TITLE
Not able to hide [share,Like,WatchLater] Button toolbar

### ISSUE THREAD

**Issue by PrabhuCE** [u-wave/react-vimeo#102]
Play, Progress, Volume should be there but toolbar should be hidden.

**Comment by goto-bus-stop** [comment]
Is this possible in the official Vimeo SDK?

**Comment by PrabhuCE** [comment]
Yes, even Vimeo SDK doesn't provide this feature....

[https://developer.vimeo.com/player/sdk/embed](url)

This parameter will hide all elements in the player (play bar, sharing buttons, etc) for a chromeless experience. ⚠️ Warnings: When using this parameter, the play/pause button will be hidden. To start playback for your viewers, you'll need to either enable autoplay, use keyboard controls, or implement our player SDK to start and control playback. Note that setting this parameter will not disable keyboard controls.

Thanks for quick response
