### ISSUE TITLE
Feature request: Seek in an already started video

### ISSUE THREAD

**Issue by AugustGSP** [u-wave/react-vimeo#104]

**Comment by goto-bus-stop** [comment]
yeah the `start` prop intentionally works this way. Seeking is hard to sensibly do in a declarative way, I think, so you have to do it manually by storing the [player object](https://developer.vimeo.com/player/sdk/reference#methods-for-player-details) in a ref:

```js
function PlayerComponentThatSeeks () {
  const playerRef = React.useRef(null)

  React.useEffect(() => {
    if (<conditions>)
      playerRef.current.setCurrentTime(theTimeToSeekToInSeconds)
  }, <dependencies>)

  return (
    <Vimeo
      onReady={player => {
        playerRef.current = player
      }}
    />
  )
}
```

**Comment by AugustGSP** [comment]
Perfect! I should have expected this, 'react-youtube' uses the same solution.

It might be a good idea to add a note about this to the readme, unless of course i'm the only one that was oblivious to this. 

Thanks!
