### ISSUE TITLE
Types are missing in published version

### ISSUE THREAD

**Issue by G07cha** [u-wave/react-vimeo#110]
First of all, thanks for great package! 🎉 
I've noticed you put an extra effort of making TypeScript typings available and accurate which is really helpful but when I look at [latest available version](https://registry.npmjs.org/@u-wave/react-vimeo/-/react-vimeo-0.8.3.tgz) they seem to be missing there. I assume it got lost somewhere during publishing process, could you please publish them as well in next version?

**Comment by goto-bus-stop** [comment]
Oh, I hadn't done a release yet after adding the types. Now out as 📦 0.9.0. thanks for reminding me!

**Comment by 1stevengrant** [comment]
looks like this is needing to be done again. Types in `master` branch are correct but in the tagged `0.9.10` they're off.
