### ISSUE TITLE
Add documentation for authorization for private video display.

### ISSUE THREAD

**Issue by JasonHoku** [u-wave/react-vimeo#116]
The Vimeo API for npm has authenticated header requests, implementing this feature can add moderated display via react.
https://www.npmjs.com/package/vimeo#authenticated

Is there any work already occurring for implementing Vimeo auth? And if not, would this party be interested in assistance in developing it?

**Comment by goto-bus-stop** [comment]
I think this may be out of scope as this package just uses the vimeo player SDK. If the player SDK does not have a feature for this, I would be unlikely to implement it in this package.

**Comment by byteab** [comment]
@goto-bus-stop not sure how to handle private videos 
need to pass a token as a header
