### ISSUE TITLE
quality=360p param is not working.

### ISSUE THREAD

**Issue by devendratata** [u-wave/react-vimeo#119]
In video prop as mentioned in the document, I am passing URL along with quality parameter, but when it's loaded it's not considering the quality param

`import Vimeo from "@u-wave/react-vimeo";

<Vimeo
                              ref={playerRef}
                              className="custom-vimeo-player"
                              video={`https://player.vimeo.com/video/${vimeoId}?quality=360p`}
                              paused={playerProps.paused}
                              onTimeUpdate={handleTimeUpdate}
                              onProgress={handleProgress}
                              onPlay={handlePlay}
                              onError={onError}
                            />`

**Comment by goto-bus-stop** [comment]
Yeah, when passing a URL to `video`, react-vimeo actually only extracts the video ID from it.

I don't know if there's a way to do this with the Vimeo SDK, which this module uses. If [`@vimeo/player`](https://github.com/vimeo/player.js) does have a quality option, we should expose it as a prop here.

**Comment by devendratata** [comment]
There is a method called "setQuality", can we expose that here?

**Comment by iuriandreazza** [comment]
Hi, I´ve added the support for quality in the PR: https://github.com/u-wave/react-vimeo/pull/132 :) had the same issue, and after some debug got that the param was not mapped for the player.

Hope that helps.
