### ISSUE TITLE
Request add option to remove tracking

### ISSUE THREAD

**Issue by DanjelvdWal** [u-wave/react-vimeo#121]
Would it be possible to add the "dnt" property from the vimeo player?

https://github.com/vimeo/player.js/ find: "dnt".
"Block the player from tracking any session data, including cookies.".

That would be really great!

**Comment by goto-bus-stop** [comment]
it would be, PR welcome :)

**Comment by goto-bus-stop** [comment]
Released in 📦 0.9.3. thanks!
