### ISSUE TITLE
onReady player.getDuration rounded, EXACT after playing.

### ISSUE THREAD

**Issue by alex20465** [u-wave/react-vimeo#123]
The `player.getDuration()` on `onReady` event returns rounded seconds, meanwhile after playing, `player.getDuration()` returns the exact correct seconds.

```
onready, getDuration() output: 31.000
onplay, getDuration() output: 30.699
```

If this is desired, close this issue.

**Comment by goto-bus-stop** [comment]
`player` is an instance of [`@vimeo/player`](https://www.npmjs.com/package/@vimeo/player), so it should have all the same behaviours.
