### ISSUE TITLE
How to make autoplay keep fullscreen mode?

### ISSUE THREAD

**Issue by anajuliabit** [u-wave/react-vimeo#124]
Steps:
- Activate autoplay
- Setup fullscreen mode

When go to next video, vimeo gets out fullscreen mode and display this error:
```
Uncaught (in promise) Error: Unknown player. Probably unloaded.
    at readyPromise (player.es.js:1458)
    at new Promise (<anonymous>)
    at Player.ready (player.es.js:1457)
    at HTMLDocument.<anonymous> (player.es.js:1258)
```

I nedeed that just like youtube, the next video of playlist keeps in fullscreen.

**Comment by anajuliabit** [comment]
I asked on stackoverflow too and [here is the answer that I needed](https://stackoverflow.com/questions/66030076/how-to-persist-fullscreen-mode-in-browser-with-autoplay-like-youtube-playlist-do?answertab=votes#tab-top)

**Comment by loq24** [comment]
Is this possible?
