### ISSUE TITLE
 Error SourceBuffer

### ISSUE THREAD

**Issue by chla** [u-wave/react-vimeo#145]
This SourceBuffer has been removed from the parent media source.

`<Vimeo
  video={vimeoId}
  controls={false}
  responsive={true}
  loop={true}
  volume={0}
  autoplay
  autopause={false}
  paused={paused}
/>`

Chrome Version 91.0.4472.114 (Official Build) (x86_64)

<img width="1675" alt="Screen Shot 2021-07-15 at 11 13 35 PM" src="https://user-images.githubusercontent.com/1585160/125859912-2c99fe95-5451-4b37-ad65-5b5badd31cba.png">

Video is working but tons of console error. Any clue what's going on?

**Comment by chla** [comment]
adBlock was the issue

**Comment by goto-bus-stop** [comment]
That must be something in Vimeo's player implementation. This module just wraps the SDK and knows nothing about such low-level parts.
