### ISSUE TITLE
ReferenceError: VideoHandler is not defined

### ISSUE THREAD

**Issue by nagman** [u-wave/react-vimeo#152]
I'm implementing a very simple background video with your package:
```jsx
<Vimeo dnt background video="600918237" />;
```

And my console throws this:
```console
Uncaught ReferenceError: VideoHandler is not defined
    at vimeo_video_handler.js:7
```

My dependencies:
```json
"dependencies": {
  "@u-wave/react-vimeo": "^0.9.5",
  "next": "^11.1.0",
  "react": "^17.0.2",
  "react-dom": "^17.0.2",
},
```

**Comment by nagman** [comment]
Not sure if it's related, but `autopause` doesn't work neither.
Maybe because I'm using next.js?
Could it have to do with SSR, or script loading?
I've seen other issues with `VideoHandler is not defined` on the Vimeo API, and the reason seamed to be the loading of the player SDK.

**Comment by nagman** [comment]
Apparently the `autopause` issue is being addressed in another thread: https://github.com/vimeo/player.js/issues/714

**Comment by goto-bus-stop** [comment]
sorry for leaving this hanging, i suspect this is not this package's fault, but i don't really know. i will close this as stale but feel free to comment if there is still an issue.

**Comment by alexkarmhon** [comment]
Try to open in chrome
