### ISSUE TITLE
Warnings and errors

### ISSUE THREAD

**Issue by mgoldenbe** [u-wave/react-vimeo#166]
When embedding a public Vimeo video (`<Vimeo video="..." />`), I get the following:

![image](https://user-images.githubusercontent.com/24386790/137802057-5cf53a73-d6ab-417c-9784-20c3d9ce6e93.png)

**Comment by goto-bus-stop** [comment]
The vimeo SDK might expect a hex colour _without_ a `#` in front. Not totally sure, but that is the only format they list in their docs: https://developer.vimeo.com/player/sdk/embed

**Comment by mgoldenbe** [comment]
Is there an attribute I can specify in my code to get rid of this error?

**Comment by goto-bus-stop** [comment]
i don't know what your code looks like :) are you specifying a color now?

it's hard to tell if the errors are even caused by react-vimeo, but if they are, the only thing i can think of based on those logs is that you're entering an invalid `color` prop. I assume the second error line is not caused by react-vimeo at all, that looks like an issue with `video_toolbar.js`.

**Comment by mgoldenbe** [comment]
I quoted my vimeo-related code in the question:

`<Vimeo video="..." />
`

This is it on my side and there are no errors without this line.

**Comment by goto-bus-stop** [comment]
…I haven't replied because I don't know :) 

I never tried using it in an extension. Maybe this package doesn't work in extension scripts for some reason. If you/someone wants to dig into it and see what's going on…

**Comment by mgoldenbe** [comment]
What do you mean by "an extension"? This is a React library and I used it in React, i.e. its primary use. Am I missing something?

**Comment by goto-bus-stop** [comment]
I assumed you were developing a browser extension because the stack trace has a `chrome-extension://` url in it. `runtime.lastError` is also something to do with browser extensions.

**Comment by mgoldenbe** [comment]
No, I am developing a website with React.js frontend and Django backend...

**Comment by goto-bus-stop** [comment]
Oh…does the embed work correctly?

**Comment by mgoldenbe** [comment]
The video is embedded and plays, but I am not sure whether the warning and the errors can be safely ignored.

**Comment by goto-bus-stop** [comment]
OK, if there are no observable issues, it should be safe. I think you would get the same with a non-react vimeo embed.
