### ISSUE TITLE
Lazy Load Video

### ISSUE THREAD

**Issue by zolrath** [u-wave/react-vimeo#183]
### Issue:
When loading a page using react-vimeo, the waterfall of requests to vimeo is a large amount of the network tabs activity.
When performing a Lighthouse test using Chrome this has a large impact on score both for the loading as well as "Time to Interactive".

To fix these issues, Google recommends using a facade of the video player until the user attempts to interact with the video.
https://web.dev/third-party-facades/

### Desired Behavior:

Instead of immediately loading the video iFrame onto the page, display the videos thumbnail (and allow override of thumbnail via prop) with a play icon overlaid.

Once the user clicks on the play icon, smoothly (without causing size jitter on the page) swap the thumbnail out for the actual video.

**Comment by goto-bus-stop** [comment]
i would suggest doing this in a wrapper component. this component only handles the state of the vimeo player itself. i think with the callback props that are there, it is possible to implement a click-to-play thumbnail component separately.

**Comment by PratikAirflip** [comment]
Hey @zolrath Were you able to implement this?
