### ISSUE TITLE
Workspaces can only be enabled in private projects.

### ISSUE THREAD

**Issue by thebuilder** [u-wave/react-vimeo#186]
Installing this library with `yarn` results in a warning:

```
warning Workspaces can only be enabled in private projects.
```

This is because the `package.json` contains a `workspaces` definition, but the file isn't marked as `private: true` - Seems like it might be added for the Examples project?

**Comment by goto-bus-stop** [comment]
hm, that's a bit frustrating, i don't know why yarn cares about how a dependency's repo is organised. that might force me to go back to the old worse way where the example required a completely separate `npm install`…

**Comment by thebuilder** [comment]
If you are going with Workspaces, then you should have all your packages as its own workspace - Then the root package.json would be private, and could contain the scripts to build/start the project.

```
packages/react-vimeo/package.json 
packages/example/package.json
package.json
```

**Comment by goto-bus-stop** [comment]
I understand yarn wants that, but npm does not have that restriction, and it's too heavyweight for just an example imo 😄 

Found an easy way to do it without workspaces tho. Thanks for bringing this up :)

**Comment by goto-bus-stop** [comment]
📦 0.9.8 should fix it!
