### ISSUE TITLE
'Vimeo' cannot be used as a JSX component.

### ISSUE THREAD

**Issue by iammatthias** [u-wave/react-vimeo#188]
```
'Vimeo' cannot be used as a JSX component.
  Its instance type 'Vimeo' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
      Type 'import("./node_modules/@u-wave/react-vimeo/node_modules/@types/react/index").ReactNode' is not assignable to type 'React.ReactNode'.
        Type '{}' is not assignable to type 'ReactNode'.ts(2786)
```

This error has been occurring since the recent update to v0.9.6

**Comment by marcello-palmitessa** [comment]
same issue here with react 18 and react 17.0.2

**Comment by jdockwarder** [comment]
The latest release is missing React 18 in `peerDependencies`. This is apparently causing trouble. For the moment I ignore it with @ts-ignore in my Next.js App.

```json
"peerDependencies": {
    "react": "^0.14.0 || ^15.0.0 || ^16.0.0 || ^17.0.0"
}
```

**Comment by jdockwarder** [comment]
I opened a pull request for this u-wave/react-vimeo#189

**Comment by goto-bus-stop** [comment]
I think this could also be because of mismatching `@types/react` versions. 0.9.7 accepts typings from react 17 and react 18 so hopefully your package manager will install the right one for you now.
