### ISSUE TITLE
support for Chapter feature

### ISSUE THREAD

**Issue by danieleguido** [u-wave/react-vimeo#193]
Hello,
I was wondering if you planned support for Vimeo Chapters, e.g to get chapters from the player? 
https://developer.vimeo.com/player/sdk/reference#methods-for-chapters)

In alternative, do you know how the Player instance (https://github.com/u-wave/react-vimeo/blob/default/src/index.js#L124) can be exposed to the container?
(btw many thanks for this great lib!)

**Comment by goto-bus-stop** [comment]
I haven't used chapters myself so I'm not sure if/how they could be integrated as props, but suggestions are welcome.

In general you can get the player using the `onReady` prop:

```js
const [player, setPlayer] = useState(null)
useEffect(() => {
  if (player) {
    // you can access chapter methods here
  }
}, [player])

return (
  <Vimeo onReady={setPlayer} {...otherProps} />
)
```

**Comment by danieleguido** [comment]
@goto-bus-stop thank you for your swift reply, I think it's a neat solution: this way, Chapters logic can be implemented in another component. 
Having a generic method to add listeners would be nice, 
```
const { onError, onReady, subscribe } = this.props;
```
so that we can do smth like 
```
subscribe={{ chapterchange:() => {} }}
```

**Comment by danieleguido** [comment]
@goto-bus-stop it works with your solution, the `onReady`method provides me with what I needed

```javascript
const playerRef = useRef()
const [chapters, setChapters] = useState([])
const [currentChapter, setCurrentChapter] = useState(null)

const onReady = (player) => {
  if (!playerRef.current) {
    player.on('chapterchange', (chapter) => { setCurrentChapter(chapter) })
    player.getChapters()
      .then((chapters) => { setChapters(chapters) })
      .catch((error) => { console.warn(error) })
    playerRef.current = player
  }
}

const gotoChapter = (chapter) => {
  playerRef.current.setCurrentTime(chapter.startTime)
    .then(() => {
      playerRef.current.play()
    })
}
```
