### ISSUE TITLE
Unable to play videos set to private in vimeo.

### ISSUE THREAD

**Issue by jonasostrom** [u-wave/react-vimeo#198]
When trying to play a Vimeo Video that is locked

- The domain is set to approved to play the video.
- CSP Headers set.

player.es.js:811
Uncaught (in promise) Error: “https://vimeo.com/XYZ” is not embeddable. 
at XMLHttpRequest.l.onload (player.es.js:811:18)

Is there other people having problems like this?

**Comment by goto-bus-stop** [comment]
I think you need a full URL to private videos to embed them, with a `?h` parameter in the query string. @u-wave/react-vimeo doesn't yet support using full URLs. https://github.com/u-wave/react-vimeo/pull/196 will support that.
