### ISSUE TITLE
How to start the video from the beginning after pause?

### ISSUE THREAD

**Issue by bennik88** [u-wave/react-vimeo#207]
I want to pause the player and on play I want to resume the video from the start. So a restart of the video after it was paused. But how can I access if the video should restart or manipulate the current time?
I only found `start` which is not working when setting it at `0`.

```js
<Vimeo
        onPause={() => {
          console.log("playing");
         // SET VIDEO TO RESTART 
          setStart(0);
        }}
        video={videoId}
        paused={!isFocused}
        start={start}
        muted={true}
        responsive={true}
        loop={true}
        showPortrait={false}
        showTitle={false}
        controls={false}
        background={true}
      />
```

**Comment by goto-bus-stop** [comment]
`start` is a slightly strange prop because it only applies when the video changes.

to do what you want you'll need to access the vimeo player instance directly. you can store it with `onReady` and then use the `setCurrentTime` method.

```js
const [player, setPlayer] = useState()

return (
  <Vimeo
    onReady={setPlayer}
    onPause={() => player.setCurrentTime(0)}
  />
)
```
