### ISSUE TITLE
controls prop has no effect or is not well documented

### ISSUE THREAD

**Issue by gordonCharles** [u-wave/react-vimeo#208]
The controls prop is documented as:

Name      | Type  |  Default  |  Description
--------------------------------------------------------------------------------------------
controls  | bool   |  true        | Hide all elements in the player (play bar, sharing buttons, etc).
--------------------------------------------------------------------------------------------
Changes to the value of controls (true or false) has no effect on the objects I've highlighted on the attached image.  Either the documentation is for something else and is not sufficiently clear or prop has no effect.

`import React from "react";
import Vimeo from "@u-wave/react-vimeo";

export default function App() {

  return (
    <div className="App">
      <Vimeo
        video="245095318"
        showTitle={false}
        showPortrait={false}
        showByline={false}
        controls={true}
        playsInline={false}
        width={"500"}
      />
    </div>
  );
}`

![react-vimeo_issue](https://user-images.githubusercontent.com/12214361/184032276-4e3af97e-2676-4bfe-9225-de76ce02dc64.jpg)

**Comment by jgalianoz** [comment]
+1

**Comment by goto-bus-stop** [comment]
The `controls` prop maps directly to the `controls` option in the vimeo player SDK.
https://github.com/vimeo/player.js#embed-options

> This parameter will hide all elements in the player (play bar, sharing buttons, etc) for a chromeless experience. ⚠️Warning: When using this parameter, the play bar and UI will be hidden. To start playback for your viewers, you'll need to either enable autoplay or use our player SDK to start and control playback. **(available to Plus, PRO, or Business members)**

so if you're not a paying vimeo customer it won't work.

**Comment by vyas-meet** [comment]
> The `controls` prop maps directly to the `controls` option in the vimeo player SDK. https://github.com/vimeo/player.js#embed-options
> 
> > This parameter will hide all elements in the player (play bar, sharing buttons, etc) for a chromeless experience. ⚠️Warning: When using this parameter, the play bar and UI will be hidden. To start playback for your viewers, you'll need to either enable autoplay or use our player SDK to start and control playback. **(available to Plus, PRO, or Business members)**
> 
> so if you're not a paying vimeo customer it won't work.

Thank you for sharing. Agree with the OP, it would help if this was a part of the documentation.
