### ISSUE TITLE
The autoplay don´t function in chrome

### ISSUE THREAD

**Issue by alejogs4** [u-wave/react-vimeo#21]

**Comment by goto-bus-stop** [comment]
Chrome has some new restrictions on audio playback. Sites can't play audio until the user interacts with the page. The only way to deal with it is to let users click/tap the video to start playing, or to have a button of some sort that starts the video.

**Comment by nmalancea** [comment]
Autoplay in Chrome is only allowed for muted videos.
If you're playing a video without sound just try adding the `muted` property in addition to `autoplay`, and autoplay should then work.
