### ISSUE TITLE
autoplay feature does not work on mobile or IOS devices

### ISSUE THREAD

**Issue by yash-netzoptimize** [u-wave/react-vimeo#243]
Vimeo's code to automatically start a video on the Vimeo player when loaded without having to press the play button is: autoplay. However, Vimeo states that this will not work on mobile devices or IOS devices like Safari using Vimeo's player.

**Comment by jordanellis** [comment]
I believe this is due to the browsers blocking autoplay. Safari documentation on autoplay: https://developer.apple.com/documentation/webkit/delivering_video_content_for_safari/#3030251
