### ISSUE TITLE
TypeError: _vimeoRefs_current_index.setCurrentTime is not a function

### ISSUE THREAD

**Issue by Jairwin-L** [u-wave/react-vimeo#246]
repo code: https://github.com/Jairwin-L/next-demo/commit/c9cfa33a3fecb4731595d9fd844583c075d5e214#diff-18e0d4553c97cfc420e938ccafb4e3a688e782fa4512ba4ceae3e2a6f24c1987

**Comment by goto-bus-stop** [comment]
yeah in react the `ref` accesses the component instance, not the vimeo player. you can get the video player in the `onReady` callback. https://github.com/u-wave/react-vimeo/issues/221#issuecomment-1275762857

**Comment by Jairwin-L** [comment]
when multiple videos are switched and replayed, there will still be some videos that cannot be played from 0
