### ISSUE TITLE
Video controls color

### ISSUE THREAD

**Issue by VadimGordeev** [u-wave/react-vimeo#254]
Why controls color doesn`t change? Here is my code 

` <Vimeo
          video="76979871"
          autoplay
          color="#ce3591ff"
        />`

**Comment by goto-bus-stop** [comment]
I'm not sure if the hex + alpha syntax is supported by vimeo. Maybe try it with `color="ce3591"`, without the alpha component.

Some videos also don't support changing colour at all, if their uploader has a paid account and configured a controls colour for the video.

**Comment by VadimGordeev** [comment]
> I'm not sure if the hex + alpha syntax is supported by vimeo. Maybe try it with `color="ce3591"`, without the alpha component.
> 
> Some videos also don't support changing colour at all, if their uploader has a paid account and configured a controls colour for the video.

That helped! Thank you
