### ISSUE TITLE
Does this not work for Live events?

### ISSUE THREAD

**Issue by Sa-So** [u-wave/react-vimeo#269]
I have got an embed link for a live event created via Vimeo
https://vimeo.com/event/4325559/embed/1281fff32a
and I get this error:
![image](https://github.com/u-wave/react-vimeo/assets/60461699/adfe120d-aa52-43c5-9b83-271378af2641)
where it fails:
![image](https://github.com/u-wave/react-vimeo/assets/60461699/74b389b0-0cf9-4767-9922-fe0668b4ea1a)
Are live events not supported or am I doing something wrong here?

**Comment by goto-bus-stop** [comment]
indeed, that seems to be accurate: https://github.com/u-wave/react-vimeo/issues/153

closing as duplicate :)
