### ISSUE TITLE
React 19.0 incompatibility

### ISSUE THREAD

**Issue by kevinowyang** [u-wave/react-vimeo#281]
the command
 **npm install --save @u-wave/react-vimeo**
create error as follows.

**npm error code ERESOLVE  
npm error ERESOLVE unable to resolve dependency tree  
npm error
npm error While resolving: curved-centauri@0.0.1
npm error Found: react@19.0.0
npm error node_modules/react
npm error   react@"^19.0.0" from the root project
npm error
npm error Could not resolve dependency:
npm error peer react@"^0.14.0 || ^15.0.0 || ^16.0.0 || ^17.0.0 || ^18.0.0" from @u-wave/react-vimeo@0.9.11
npm error node_modules/@u-wave/react-vimeo
npm error   @u-wave/react-vimeo@"*" from the root project**

**Comment by goto-bus-stop** [comment]
Released in 📦 0.9.12. Thanks!
