### ISSUE TITLE
Set "Start-Time" (#t=60s)

### ISSUE THREAD

**Issue by fedbalves** [u-wave/react-vimeo#3]
Hi guys.
How can I config my Component to start Video from some point?
Thx!

**Comment by goto-bus-stop** [comment]
This is not implemented yet but I need it too for my use case. I'll have a look right now.

**Comment by goto-bus-stop** [comment]
📦 0.3.1 has a `start` prop that allows you to start playing a video at a given time in seconds. It does not seek if you change the `start` prop while playing; if you also need that we should add a `seekTo()` method to the component, I think, and then you could use a ref to call that method. lmk if that would be necessary for your use case.

**Comment by fedbalves** [comment]
Thx! I'll try that and return you a feedback.
Thanks again!
