### ISSUE TITLE
Is there a way to enableTextTrack()?

### ISSUE THREAD

**Issue by clouditinerary** [u-wave/react-vimeo#61]
Hello - thanks for producing this excellent package... In the Vimeo player SDK there is a function enableTextTrack() that allows the programmer to programmatically trigger the subtitles/captions track on a video - is this possible through react-vimeo? I do not see this option in the docs 

Thanks again, 
G

**Comment by goto-bus-stop** [comment]
react-vimeo doesn't support that right now no. The `onReady()` prop was supposed to allow you to directly manipulate the Vimeo player instance, but I just noticed that it never gets called, so that doesn't help…

I've not used text tracks myself and I'm not sure how they work, but it would be nice if we could provide a prop for it somehow. Maybe `textTrack={{type: 'subtitle', language: 'en'}}`, or an array if Vimeo supports more than 1.

**Comment by clouditinerary** [comment]
This is what I got from Vimeo support (on 5.11.18) :

The latest version of Player.JS allows developers to toggle subtitles/caption (named "texttracks" in our APIs). Learn more about the ability here:

[https://github.com/vimeo/player.js#enabletexttracklanguage-string-kind-string-promiseobject-invalidtracklanguageerrorinvalidtrackerrorerror](https://github.com/vimeo/player.js#enabletexttracklanguage-string-kind-string-promiseobject-invalidtracklanguageerrorinvalidtrackerrorerror)

And you can read more about texttracks here:
[https://developer.vimeo.com/api/upload/texttracks](https://developer.vimeo.com/api/upload/texttracks)

I guess react-vimeo would first need to upgrade to the latest Player version and according the documentation above integrating this should be relatively simple. It seems like the props as you suggest make sense.

Thanks! 
G

**Comment by clouditinerary** [comment]
Hi there @goto-bus-stop - have you had a chance to consider adding this? Thank you!

**Comment by goto-bus-stop** [comment]
v0.6.0 fixed the `onReady(player)` callback, so you can do something like

```js
<Vimeo
  onReady={player => this.setState({ player })}
  {...otherProps}
/>
```

and call `this.state.player.enableTextTrack(...)` in the parent component. I think that'll do until someone who knows better than me how text tracks work contributes a dedicated prop for it:)
