### ISSUE TITLE
Can't set iframe width to 100%

### ISSUE THREAD

**Issue by austindenny** [u-wave/react-vimeo#66]
<img width="438" alt="screen shot 2018-11-25 at 11 02 28 am" src="https://user-images.githubusercontent.com/9449641/48981975-f542d980-f0a1-11e8-95d2-9744294f9b8e.png">

It looks like the Vimeo component is passing className to the containing div, rather than the player it renders, and PropTypes prevent a percent value on width/height. Hoping to pass a percent to the iframe itself to allow a simpler responsive element. 

<img width="392" alt="screen shot 2018-11-25 at 11 37 46 am" src="https://user-images.githubusercontent.com/9449641/48982331-a9defa00-f0a6-11e8-9b75-887330b94d30.png">

**Comment by luchocab** [comment]
I do not know if it's the solution but...
I have found this for responsive.

This is the SCSS
```
video{ 
    position: relative;
  padding-bottom: 56.25%;
  padding-top: 0;
  height: 0;
  overflow: hidden;
  iframe {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
  }
}
```

This is the component
```
<Vimeo className="video" video="ID_HERE"  />
```

 worked for me!

**Comment by TimFletcher** [comment]
Yeah, this works just fine now with the `responsive` prop.

```js
<Vimeo video={videoId} responsive />
```

**Comment by goto-bus-stop** [comment]
nice hopefully that should do it then for most people :+1:

**Comment by jgalianoz** [comment]
The Responsive property works perfectly on desktop but on mobile, it does not cover 100% of the device's height.
