### ISSUE TITLE
Restarting the player

### ISSUE THREAD

**Issue by benjick** [u-wave/react-vimeo#67]
First of all, thanks for creating this package and react-youtube, really nice to work with.

The problem I have is that I use these in a carrousel and I'm not sure how to restart a video when it comes back to the slide again. Currently I'm just rendering the current one + the next one. The current one has autoplay, the next one has autoplay + paused = true.

This works kinda well, but I would like to keep them all in the DOM. How would I start a video from the beginning?

**Comment by goto-bus-stop** [comment]
that stuff is kinda hard with a declarative API. The `onReady()` callback gives access to the raw player object which you can use to play/pause/seek as needed. it could work to mount all the players with `paused`, then use the player object to start the focused one when it slides in.

**Comment by benjick** [comment]
Thanks, just what I was looking for, I see now that it was stated in the docs too. Cheers!
