### ISSUE TITLE
Can't start a second video dynamically

### ISSUE THREAD

**Issue by t-hjalmar** [u-wave/react-vimeo#68]
Hello,

I'm having an issue if a video is playing and I want to change the Vimeo ID with a different start time dynamically. Doing this gives me an error and plays the second video from the beginning. I'm attaching the error and a basic example where this happens.

**Note**: If the first video starts from the beginning there won't be any error but on click the second video won't start at the set start time.

![screen shot 2018-12-13 at 12 05 43 pm](https://user-images.githubusercontent.com/45855461/49954887-85b95080-fecf-11e8-9d8a-089716fd7f58.png)

This is the code.

```
import React, { Component } from 'react';
import './App.css';
import Vimeo from '@u-wave/react-vimeo'

class App extends Component {

constructor (props) {
  super(props)
  this.state = {
    'startTime':40,
    'videoCode':77677392
  }
  
}

changeVideo = () => {
  this.setState({
    'videoCode': 304038551,
    'startTime': 60,
  })
}

  render() {
    return (
      <div className="App embed-responsive embed-responsive-16by9">
        <Vimeo width={640} height={480} video={this.state.videoCode} start={this.state.startTime} autoplay></Vimeo>
        <button onClick={this.changeVideo}>Toggle video</button>
      </div>
    );
  }
}

export default App;
```

Thanks for the help

**Comment by Odelya** [comment]
Same by me :-(

**Comment by goto-bus-stop** [comment]
I think the cause is probably that the component is applying the startTime and videoId parameters in the wrong order. Didn't look at a solution yet.

**Comment by goto-bus-stop** [comment]
:package: 0.8.2 has an attempted fix
