### ISSUE TITLE
Make vimeo player peer dependency

### ISSUE THREAD

**Issue by androiderik** [u-wave/react-vimeo#77]
it would be better if we could control the vimeo/player version.
i recently realize that there are new configs deployed to the new vimeo versions, that we can't interact to.

**Comment by goto-bus-stop** [comment]
I don't think that would change anything. The peer dependency would have to be the same version range as the current dependency. New options would have to be added to this package's props to be usable even if the player module was a peer dependency.

If it gets outdated in your `node_modules` you can update it by reinstalling this package or by doing `npm update --depth 2 @vimeo/player`.

If there are missing props please open issues or PRs to add those
