### ISSUE TITLE
IE11 - Object doesn't support property or method 'load'

### ISSUE THREAD

**Issue by gavinkilbride** [u-wave/react-vimeo#89]
Is anyone aware of any issues with IE11?

I'm getting the following error:
![image](https://user-images.githubusercontent.com/831616/65578173-9ea37600-dfb8-11e9-9e14-40da8e93a487.png)

I have the IE Polyfills for React and everything else is running as expected.

**Comment by goto-bus-stop** [comment]
I think that's happening inside vimeo's iframe? This module doesn't load anything from vimeocdn.com directly.
Does it also happen on other embedded vimeo videos, like if you copy/paste an embed code instead of using react-vimeo?

**Comment by gavinkilbride** [comment]
@goto-bus-stop you're quite right, the issue is with the Vimeo embed. I added a simple vimeo iframe and it still crashed. Interestingly it's not just (crappy) IE that fails. Firefox and Edge also crash the player.

**Comment by gavinkilbride** [comment]
Ok, I got the the bottom of it. I'm running Windows N Enterprise and it doesn't come with the Media Feature Pack. https://support.mozilla.org/en-US/kb/fix-video-audio-problems-firefox-windows?as=u&utm_source=inproduct
Thanks for the help.
