### ISSUE TITLE
Video with private link privacy does not load

### ISSUE THREAD

**Issue by rrsilaya** [u-wave/react-vimeo#92]
Video with private link privacy does not load the player and does not produce any console errors nor call the `onError` callback.

![image](https://user-images.githubusercontent.com/17796315/72951119-4b0b3280-3dc8-11ea-80f2-77279c7759ea.png)

I've supplied the `xxxxx/xxxxx` format provided from Vimeo. Noting that using the first section (the xxx's before `/`) of the ID produces 404 in the `oembed.json`.

**Comment by rrsilaya** [comment]
Solved by supplying the video URL instead of the video ID only.

**Comment by srish** [comment]
@rrsilaya Could you share an example url? I am using something like `https://vimeo.com/videoid` and it does not work for me.

**Comment by goto-bus-stop** [comment]
The `video={}` value is passed directly to the Vimeo Player API. This comment suggests that for private videos, `https://vimeo.com/videoid/privateid` should work: https://github.com/vimeo/player.js/issues/396#issuecomment-470650026
