### ISSUE TITLE
`controls={false}` does not work as intended

### ISSUE THREAD

**Issue by srish** [u-wave/react-vimeo#99]
My vimeo component looks like this right now:
```
<Vimeo
   video={id}
   showTitle={false}
   showPortrait={false}
   color='fdeaed'
   showByline={false}
   controls={false}
   width={312}
   height={185}
/>
```

I want to hide the player controls, and I'm setting `controls` as `false`,  still the controls are visible. Is this supported by `react-vimeo`?

**Comment by goto-bus-stop** [comment]
Hmm I'm seeing the same. The parameter _does_ seem to be passed down to the player correctly, as the `<iframe>` in the rendered output does contain a `&controls=0` query parameter.

Looking at the `controls` option for the Vimeo Player SDK: https://help.vimeo.com/hc/en-us/articles/360001494447-Using-Player-Parameters, it says:

> Video must be hosted by a Plus account or higher. 

Could that be the issue?

**Comment by srish** [comment]
@goto-bus-stop I am on a basic account right now (as our app is in its initial stage) and your response explains why I'm not able to get the controls to hide. Thanks! This task can be closed then :)
